# defaults used for training POYO
# this file needs to be combined with a model config and a dataset config

# Paths
data_root: ./data/processed/
log_dir: ./logs

# Transforms
train_transforms: []
eval_transforms: []

# Training
epochs: 1000
batch_size: 64
eval_epochs: 10  # frequency for doing validation
eval_batch_size: null  # if null, will use batch_size
seed: 42  # use to set random seed
sanity_check_validation: false  # if true, will start the run with validation 

optim:
  base_lr: 3.125e-5  # scaled linearly by batch size
  weight_decay: 1e-4
  lr_decay_start: 0.5  # fraction of epochs before starting LR decay

# Logging
wandb:
  enable: true
  entity: null
  project: poyo
  run_name: null
  log_model: false

# GPU and CPU
precision: 32
nodes: 1
gpus: 2
num_workers: 8

# Checkpointing
ckpt_path:  null # ./logs/poyo/bc41dgwi/checkpoints/epoch=354-step=57510.ckpt # null # poyo_mp.ckpt  
# for resuming training, or loading a model during finetuning
finetuning:
  enable: False  # must specify ckpt_path if you want to finetune
  freeze_perceiver_until_epoch: 100
  # ^ Num of epochs to freeze perceiver network while finetuning
  # -1 => Keep frozen, i.e. perform Unit-identification
  #  0 => Train everything
  # >0 => Only train unit/session embeddings for first few epochs,
  #       and then train everything
