# Center-out reaching 
# to get manifest:
# find hisham_big_dataset/ -type f -name "*.h5" | sed "s|^hisham_big_dataset/||" | sed 's/\.h5$//' | sed 's/^/- /' > manifest.txt
# to sort manifest by line length(ie separate out different tasks)
- selection:
  - brainset: hisham_big_dataset
    sessions:
    - n_20200127_center_out_reaching
    - n_20200130_center_out_reaching
    - n_20200204_center_out_reaching
    - n_20200205_center_out_reaching
    - n_20200206_center_out_reaching
    - n_20200222_center_out_reaching
    - n_20200224_center_out_reaching
    - n_20200225_center_out_reaching
    - n_20200624_center_out_reaching
    - n_20200626_center_out_reaching
    - n_20200708_center_out_reaching
    - n_20200731_center_out_reaching
    - n_20200812_center_out_reaching
    - n_20200824_center_out_reaching
    - n_20200826_center_out_reaching
    - n_20200827_center_out_reaching
    - n_20200828_center_out_reaching
    - n_20200916_center_out_reaching
    - n_20200918_center_out_reaching
    - n_20200921_center_out_reaching
    - n_20200922_center_out_reaching
    - n_20200923_center_out_reaching
    - n_20200924_center_out_reaching
    - n_20200928_center_out_reaching
    - n_20200929_center_out_reaching
    - n_20201002_center_out_reaching
    - n_20201007_center_out_reaching
    - n_20201012_center_out_reaching
    - n_20201016_center_out_reaching
    - n_20201021_center_out_reaching
    - n_20201023_center_out_reaching
    - n_20201027_center_out_reaching
    - n_20201103_center_out_reaching
    - n_20201105_center_out_reaching
    - n_20201109_center_out_reaching
    - n_20201116_center_out_reaching
    - n_20201117_center_out_reaching
    - n_20201125_center_out_reaching
    - n_20201202_center_out_reaching
    - n_20201203_center_out_reaching
    - n_20201204_center_out_reaching
    - n_20201211_center_out_reaching
    - n_20201214_center_out_reaching
    - n_20210104_center_out_reaching
    - n_20210105_center_out_reaching
    - n_20210106_center_out_reaching
    - n_20210108_center_out_reaching
    - n_20210111_center_out_reaching
    - n_20210113_center_out_reaching
    - n_20210118_center_out_reaching
    - n_20210120_center_out_reaching
    - n_20210123_center_out_reaching
    - n_20210126_center_out_reaching
    - n_20210127_center_out_reaching
    - n_20210202_center_out_reaching
    - n_20210203_center_out_reaching
    - n_20210223_center_out_reaching
    - n_20210224_center_out_reaching
    - n_20210225_center_out_reaching
    - n_20210226_center_out_reaching
    - n_20210227_center_out_reaching
    - n_20210303_center_out_reaching
    - n_20210309_center_out_reaching
    - n_20210313_center_out_reaching
    - n_20210317_center_out_reaching
    - n_20210323_center_out_reaching
    - n_20210324_center_out_reaching
    - n_20210329_center_out_reaching
    - n_20210330_center_out_reaching
    - n_20210402_center_out_reaching
    - n_20210406_center_out_reaching
    - n_20210409_center_out_reaching
    - n_20210413_center_out_reaching
    - n_20210415_center_out_reaching
    - n_20210420_center_out_reaching
    - n_20210422_center_out_reaching
    - n_20210426_center_out_reaching
    - n_20210430_center_out_reaching
    - n_20210503_center_out_reaching
    - n_20210504_center_out_reaching
    - n_20210510_center_out_reaching
    - n_20210511_center_out_reaching
    - n_20210512_center_out_reaching
    - n_20210517_center_out_reaching
    - n_20210518_center_out_reaching
    - n_20210520_center_out_reaching
    - n_20210531_center_out_reaching
    - n_20210601_center_out_reaching
    - n_20210611_center_out_reaching
    - n_20210614_center_out_reaching
    - n_20210615_center_out_reaching
    - n_20210618_center_out_reaching
    - n_20210621_center_out_reaching
    - n_20210628_center_out_reaching
    - n_20210702_center_out_reaching
    - n_20210706_center_out_reaching
    - n_20210709_center_out_reaching
    - n_20210713_center_out_reaching
    - n_20210714_center_out_reaching
    - n_20210720_center_out_reaching
    - n_20210723_center_out_reaching
    - n_20210727_center_out_reaching
    - n_20210729_center_out_reaching
    - n_20210730_center_out_reaching
    - n_20210803_center_out_reaching
    - n_20210805_center_out_reaching
    - n_20210809_center_out_reaching
    - n_20210810_center_out_reaching
    - n_20210812_center_out_reaching
    - n_20210816_center_out_reaching
    - n_20210817_center_out_reaching
    - n_20210819_center_out_reaching
    - n_20210820_center_out_reaching
    - n_20210824_center_out_reaching
    - n_20210827_center_out_reaching
    - n_20210830_center_out_reaching
    - n_20210831_center_out_reaching
    - n_20210901_center_out_reaching
    - n_20210906_center_out_reaching
    - n_20210907_center_out_reaching
    - n_20210908_center_out_reaching
    - n_20210913_center_out_reaching
    - n_20210914_center_out_reaching
    - n_20210915_center_out_reaching
    - n_20210921_center_out_reaching
    - n_20210924_center_out_reaching
    - n_20211001_center_out_reaching
    - n_20211005_center_out_reaching
    - n_20211006_center_out_reaching
    - n_20211007_center_out_reaching
    - n_20211008_center_out_reaching
    - n_20211019_center_out_reaching
    - n_20211025_center_out_reaching
    - n_20211026_center_out_reaching
    - n_20211027_center_out_reaching
    - n_20211101_center_out_reaching
    - n_20211102_center_out_reaching
    - n_20211112_center_out_reaching
    - n_20211116_center_out_reaching
    - n_20211123_center_out_reaching
    - n_20211129_center_out_reaching
    - n_20211215_center_out_reaching
    - n_20220110_center_out_reaching
    - n_20220112_center_out_reaching
    - n_20220114_center_out_reaching
    - n_20220117_center_out_reaching
    - n_20220120_center_out_reaching
    - n_20220124_center_out_reaching
    - n_20220128_center_out_reaching
    - n_20220131_center_out_reaching
    - n_20220204_center_out_reaching
    - n_20220207_center_out_reaching
    - n_20220211_center_out_reaching
    - n_20220228_center_out_reaching
    - n_20220307_center_out_reaching
    - n_20220314_center_out_reaching
    - n_20220316_center_out_reaching
    - n_20220318_center_out_reaching
    - n_20220321_center_out_reaching
    - n_20220328_center_out_reaching
    - n_20220401_center_out_reaching
    - n_20220404_center_out_reaching
    - n_20220411_center_out_reaching
    - n_20220418_center_out_reaching
    - n_20220420_center_out_reaching
    - n_20220425_center_out_reaching
    - n_20220427_center_out_reaching
    - n_20220509_center_out_reaching
    - n_20220525_center_out_reaching
    - n_20220608_center_out_reaching
    - n_20220610_center_out_reaching
    - n_20220613_center_out_reaching
    - n_20220617_center_out_reaching
    - n_20220620_center_out_reaching
    - n_20220627_center_out_reaching
    - n_20220829_center_out_reaching
    - n_20220901_center_out_reaching
    - n_20220902_center_out_reaching
    - n_20220907_center_out_reaching
    - n_20220909_center_out_reaching
    - n_20220912_center_out_reaching
    - n_20220913_center_out_reaching
    - n_20220914_center_out_reaching
    - n_20220916_center_out_reaching
    - n_20220919_center_out_reaching
    - n_20220923_center_out_reaching
    - n_20220926_center_out_reaching
    - n_20220927_center_out_reaching
    - n_20221003_center_out_reaching
    - n_20221010_center_out_reaching
    - n_20221017_center_out_reaching
    - n_20221019_center_out_reaching
    - n_20221024_center_out_reaching
    - n_20221026_center_out_reaching
    - n_20221027_center_out_reaching
    - n_20221107_center_out_reaching
    - n_20221209_center_out_reaching
    - n_20231102_center_out_reaching
  config:
    eval_subtask_index: 2


# Random target reaching
- selection:
  - brainset: hisham_big_dataset
    sessions:
    - n_20200228_random_target_reaching
    - n_20200302_random_target_reaching
    - n_20200310_random_target_reaching
    - n_20200312_random_target_reaching
    - n_20200313_random_target_reaching
    - n_20200317_random_target_reaching
    - n_20200318_random_target_reaching
    - n_20200319_random_target_reaching
    - n_20200320_random_target_reaching
    - n_20200728_random_target_reaching
    - n_20200729_random_target_reaching
    - n_20200804_random_target_reaching
    - n_20200808_random_target_reaching
    - n_20200811_random_target_reaching
    - n_20200822_random_target_reaching
    - n_20200829_random_target_reaching
    - n_20200831_random_target_reaching
    - n_20200904_random_target_reaching
    - n_20200905_random_target_reaching
    - n_20200906_random_target_reaching
    - n_20200907_random_target_reaching
    - n_20200912_random_target_reaching
    - n_20200919_random_target_reaching
    - n_20201212_random_target_reaching
    - n_20210121_random_target_reaching
    - n_20210122_random_target_reaching
    - n_20210216_random_target_reaching
    - n_20210305_random_target_reaching
    - n_20210310_random_target_reaching
    - n_20210312_random_target_reaching
    - n_20210316_random_target_reaching
    - n_20210319_random_target_reaching
    - n_20210322_random_target_reaching
    - n_20210331_random_target_reaching
    - n_20210405_random_target_reaching
    - n_20210407_random_target_reaching
    - n_20210412_random_target_reaching
    - n_20210414_random_target_reaching
    - n_20210421_random_target_reaching
    - n_20210428_random_target_reaching
    - n_20210505_random_target_reaching
    - n_20210519_random_target_reaching
    - n_20210524_random_target_reaching
    - n_20210525_random_target_reaching
    - n_20210526_random_target_reaching
    - n_20210604_random_target_reaching
    - n_20210608_random_target_reaching
    - n_20210609_random_target_reaching
    - n_20210616_random_target_reaching
    - n_20210617_random_target_reaching
    - n_20210624_random_target_reaching
    - n_20210626_random_target_reaching
    - n_20210629_random_target_reaching
    - n_20210630_random_target_reaching
    - n_20210701_random_target_reaching
    - n_20210703_random_target_reaching
    - n_20210707_random_target_reaching
    - n_20210708_random_target_reaching
    - n_20210712_random_target_reaching
    - n_20210715_random_target_reaching
    - n_20210716_random_target_reaching
    - n_20210719_random_target_reaching
    - n_20210721_random_target_reaching
    - n_20210726_random_target_reaching
    - n_20210728_random_target_reaching
    - n_20210731_random_target_reaching
    - n_20210802_random_target_reaching
    - n_20210804_random_target_reaching
    - n_20210811_random_target_reaching
    - n_20210818_random_target_reaching
    - n_20210823_random_target_reaching
    - n_20210825_random_target_reaching
    - n_20210903_random_target_reaching
    - n_20210917_random_target_reaching
    - n_20211015_random_target_reaching
    - n_20211022_random_target_reaching
    - n_20211029_random_target_reaching
    - n_20211210_random_target_reaching
    - n_20220119_random_target_reaching
    - n_20220121_random_target_reaching
    - n_20220126_random_target_reaching
    - n_20220202_random_target_reaching
    - n_20220203_random_target_reaching
    - n_20220209_random_target_reaching
    - n_20220210_random_target_reaching
    - n_20220221_random_target_reaching
    - n_20220224_random_target_reaching
    - n_20220225_random_target_reaching
    - n_20220311_random_target_reaching
    - n_20220317_random_target_reaching
    - n_20220323_random_target_reaching
    - n_20220325_random_target_reaching
    - n_20220330_random_target_reaching
    - n_20220331_random_target_reaching
    - n_20220405_random_target_reaching
    - n_20220406_random_target_reaching
    - n_20220407_random_target_reaching
    - n_20220408_random_target_reaching
    - n_20220413_random_target_reaching
    - n_20220414_random_target_reaching
    - n_20220415_random_target_reaching
    - n_20220421_random_target_reaching
    - n_20220422_random_target_reaching
    - n_20220428_random_target_reaching
    - n_20220429_random_target_reaching
    - n_20220510_random_target_reaching
    - n_20220511_random_target_reaching
    - n_20220513_random_target_reaching
    - n_20220523_random_target_reaching
    - n_20220526_random_target_reaching
    - n_20220527_random_target_reaching
    - n_20220530_random_target_reaching
    - n_20220531_random_target_reaching
    - n_20220601_random_target_reaching
    - n_20220602_random_target_reaching
    - n_20220606_random_target_reaching
    - n_20220614_random_target_reaching
    - n_20220616_random_target_reaching
    - n_20220623_random_target_reaching
    - n_20220831_random_target_reaching
    - n_20220906_random_target_reaching
    - n_20220921_random_target_reaching
    - n_20220928_random_target_reaching
    - n_20220930_random_target_reaching
    - n_20221007_random_target_reaching
    - n_20221012_random_target_reaching
    - n_20221014_random_target_reaching
    - n_20221021_random_target_reaching
    - n_20221025_random_target_reaching
    - n_20221028_random_target_reaching
    - n_20221101_random_target_reaching
    - n_20221102_random_target_reaching
    - n_20221104_random_target_reaching
    - n_20221109_random_target_reaching
    - n_20221130_random_target_reaching
    - n_20230110_random_target_reaching
    - n_20230113_random_target_reaching
    - n_20230116_random_target_reaching
    - n_20230117_random_target_reaching
    - n_20230123_random_target_reaching
    - n_20230124_random_target_reaching
    - n_20230127_random_target_reaching
    - n_20230130_random_target_reaching
    - n_20230131_random_target_reaching
    - n_20230203_random_target_reaching
    - n_20230206_random_target_reaching
    - n_20230207_random_target_reaching
    - n_20230210_random_target_reaching
    - n_20230213_random_target_reaching
    - n_20230214_random_target_reaching
    - n_20230220_random_target_reaching
    - n_20230224_random_target_reaching
    - n_20230306_random_target_reaching
    - n_20230310_random_target_reaching
    - n_20230313_random_target_reaching
    - n_20230314_random_target_reaching
    - n_20230317_random_target_reaching
    - n_20230320_random_target_reaching
    - n_20230324_random_target_reaching
    - n_20230327_random_target_reaching
    - n_20230328_random_target_reaching
    - n_20230404_random_target_reaching
    - n_20230405_random_target_reaching
    - n_20230407_random_target_reaching
    - n_20230411_random_target_reaching
    - n_20230413_random_target_reaching
    - n_20230414_random_target_reaching
    - n_20230417_random_target_reaching
    - n_20230425_random_target_reaching
    - n_20230426_random_target_reaching
    - n_20230502_random_target_reaching
    - n_20230508_random_target_reaching
    - n_20230517_random_target_reaching
    - n_20230519_random_target_reaching
    - n_20230606_random_target_reaching
    - n_20230608_random_target_reaching
    - n_20230612_random_target_reaching
    - n_20230613_random_target_reaching
    - n_20230616_random_target_reaching
    - n_20230619_random_target_reaching
    - n_20230620_random_target_reaching
    - n_20230621_random_target_reaching
    - n_20230622_random_target_reaching
    - n_20231211_random_target_reaching
    - n_20231213_random_target_reaching
    - n_20240116_random_target_reaching
    - n_20240205_random_target_reaching
  config:
    eval_subtask_index: 0